### ISSUE TITLE
Hiding particular icons

### ISSUE THREAD

**Issue by ikuraj** [wincinderith/topicons#1]
It would be very helpful to allow hiding particular icons from _topicons_ with the _icon-hider_ extension (or perhaps achieve similar behaviour). Is that possible and how hard would it be?
There is [a related issue](https://github.com/ikalnitsky/gnome-shell-extension-icon-hider/issues/19) reported in that repository.

**Comment by zliebersbach** [comment]
Thanks for the input, I'll look into this when I find some spare time. It certainly sounds like a worthwhile feature.

**Comment by ikuraj** [comment]
Awesome, looking forward to news on this! :+1:

**Comment by zliebersbach** [comment]
@kaptoxic This feature has been implemented in the latest commit. Thanks again for the suggestion!
