### ISSUE TITLE
Not working immediately on upgrade with GNOME 3.26 and Wayland, notificationDaemon._trayManager is undefined

### ISSUE THREAD

**Issue by rhertzog** [wincinderith/topicons#13]
I upgraded my Debian unstable system and GNOME went to 3.26. Topicons was not working, I upgraded the extension to version 30 (through the extensions.gnome.org website) and it still did not work. I saw this message:
```
oct. 26 14:52:14 x260-buxy gnome-shell[1962]: Source ID 14299 was not found when attempting to remove it
oct. 26 14:52:14 x260-buxy gnome-shell[1962]: ../../../../gobject/gsignal.c:2641: instance '0x56171c9e3a60' has no handler with id '108774'
oct. 26 14:52:14 x260-buxy gnome-shell[1962]: Extension "topIcons@adel.gadllah@gmail.com" had error: TypeError: notificationDaemon._trayManager is undefined
oct. 26 14:52:14 x260-buxy gnome-software[2233]: no app for changed topIcons@adel.gadllah@gmail.com
```

**Comment by rhertzog** [comment]
After a logout, it works again. I'm using Wayland. Maybe it's related... before logging out I wanted to restart the Shell with ALT+F2 then "r" but I got a message saying that restarting the shell was not supported under Wayland.

**Comment by zliebersbach** [comment]
I think you must be using another fork of the repository, since as far as I am aware this extension has not been added to the GNOME extensions website. Closing.

**Comment by rhertzog** [comment]
Weird. https://extensions.gnome.org/extension/495/topicons/ is what I'm using. I'm wondering what is the canonical repository for this extension then...
