### ISSUE TITLE
defaults don't match the original topicons plugin

### ISSUE THREAD

**Issue by oconnor663** [wincinderith/topicons#3]
Here's what I see by default from this repo:

![image](https://cloud.githubusercontent.com/assets/860932/14434374/6c57f18c-ffe0-11e5-88c8-be3361888eeb.png)

And here's what I see if I install [the original](https://extensions.gnome.org/extension/495/topicons/):

![image](https://cloud.githubusercontent.com/assets/860932/14434387/80838bbc-ffe0-11e5-972a-7d63ca49d1bc.png)

I don't have a strong preference for padding, but I notice that the default icon size in this repo clips one of my icons. (Could easily be the package's fault for not using a standard size. Not sure.)

**Comment by zliebersbach** [comment]
I'm fairly sure (just by looking at the icon) that it isn't square, which would be the reason for the cropping. 

However, if it works when the padding is changed then I don't see the issue. Changing the defaults is not really a fix, and it comes down to personal preference. If you prefer the defaults of the original topicons then perhaps you should use that one.
