### ISSUE TITLE
icons disappear in activities overview (Super)

### ISSUE THREAD

**Issue by schlichtanders** [wincinderith/topicons#8]
It would be great if the icons stay in the overview,
is that possible to fix?

**Comment by zliebersbach** [comment]
Hi, I can't seem to recreate the issue with GNOME 3.20. Would you mind posting a screen shot and the version of GNOME you're using?

**Comment by schlichtanders** [comment]
Its gnome 3.10 (the default for Ubuntu 14.04.)
it is good to know, that the issue is no longer existent for more recent versions.

The topicons are just not there in overview toppanel (as if the extension would be off), while they appear on the normal toppanel as expected

**Comment by zliebersbach** [comment]
Ah yes I get it. Doesn't seem like a major problem to me.

I have no way of easily testing older versions on my system, and I don't
particularly see the point in supporting outdated versions, so I'll close
the issue unless you'd like to have a go fixing it yourself.

**Comment by schlichtanders** [comment]
closing this topic is fine with me,
thanks for responding
all the best
